version: '3.8'

services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis-server:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis-server
  redis-chat:
    image: 1dlvb/redis-chat:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis-server
      - SPRING_DATA_REDIS_PORT=6379
      - REDIS_URI=redis://redis-server:6379
    depends_on:
      - redis-server
    restart: unless-stopped

volumes:
  redis-data:
  chat_postgres_data: